### ISSUE TITLE
EGit Update site is broken in target platform

### ISSUE THREAD

**Issue by abelgomez** [dice-project/DICE-Platform#3]
EGit Update site in the target platform points to `http://download.eclipse.org/egit/updates`, and the current target platform declares version `4.3.0.201604071810-r`.

As of the 5th of May (2016) that update site has been upgraded and now contains version `4.3.1.201605051710-r`.

Consider switching to a version-based site, e.g:
http://download.eclipse.org/egit/updates-4.3.1/ for `4.3.1.201605051710-r`
or
http://download.eclipse.org/egit/updates-4.3/ for `4.3.0.201604071810-r`
or, preferably, remove the specific EGit update Site and use the generic Mars update site (that provides version `4.1.1.201511131810-r`):
http://download.eclipse.org/releases/mars/

**Comment by abelgomez** [comment]
The attached target platform ([dice.target.zip](https://github.com/dice-project/DICE-Platform/files/252582/dice.target.zip)) contains a possible fix:
Imports EGit from the Mars update site (`4.1.1.201511131810-r`) instead of the EGit specific site.

**Comment by marcgise** [comment]
Fixed
