### ISSUE TITLE
Wrong plugin it.polimi.dice.profiles.

### ISSUE THREAD

**Issue by MicheleGuerriero** [dice-project/DICE-Platform#5]
Hi @marcgise , @abelgomez notified us at PMI about a wrong plugin currently included in the DICE-Platform called "it.polimi.dice.profiles". I've still not installed the platform, but I'm going to do this right now just to have a check. I'm absolutely not an expert using eclipse and managing eclipse's plugins, but what sound weird to me is that as far as I understood if there is such a plugin in the platform, there should be also an update site somewhere. Now the thing is that from our side (PMI) we have not released so far any plugin/update site, so I really cannot see from where that plugin comes from. It seems to be related with the DICE-Profile, but I cannot see anything about that plugin in the DICE-Profile repository (maybe here @abelgomez can confirm). So I'm wondering if you can help us in understanding from where that plugin comes from, in order to fix the issue. Thanks a lot in advance.

**Comment by MicheleGuerriero** [comment]
We found that the "it.polimi.dice.profiles" comes actually from the same plugin which installs the verification tool. This is because the verification tool needed a DTSM profile, in particular for Storm. So some time ago I provided a temporary Storm profile to verification guys so that they could start playing with it. Now the right DTSM profile for Storm has been released yesterday by ZAR, so in theory the verification tool can now switch to the proper Storm profile, but this would require some time and work to be done on the verification tool side since it is currently coupled with the previous version of the Storm profile. So I'm not sure on how to address the issue now. A possible solution could be to just leave the redundant DTSM Storm profile in order to keep the verification tool working and when the verification tool will be adapted to work with the official Storm profile we could probably release an updated version of the Platform. How does this sound?

**Comment by mbersani** [comment]
Fine to me.
It might be possible to fix the problem before the end of the month.
Let's see other comments.

Marcello

2016-06-30 11:32 GMT+02:00 Michele Guerriero notifications@github.com:

**Comment by abelgomez** [comment]
It's also fine for us to wait for its removal until the Verification tool has been migrated to the official Storm Profile.

Thus, let's leave this issue in stand by until @mbersani confirms that a new version of the platform can be built without the `it.polimi.dice.profiles` plugin.

If it's fine, I'll assign the issue to @mbersani as the responsible of the Verification tool and to @marcgise  as the responsible of packaging the DICE IDE.

**Comment by marcgise** [comment]
So summarizing, what should I do with this plugin? Should I remove it or not from the IDE in the next builds?

**Comment by mbersani** [comment]
Hello everyone!! :)

Let me consult PMI experts on this.
We'll give an answer soon.

Cheeers!

2016-07-01 8:17 GMT+02:00 Marc notifications@github.com:

**Comment by mbersani** [comment]
Hi all!

You can remove safely the fake Storm profile.
We're going to use use the newest one.

Marcello

2016-07-01 10:27 GMT+02:00 Marcello M. Bersani bersani@elet.polimi.it:

**Comment by marcgise** [comment]
Please Marcello, tell me exactly which plugin or plugins should I remove from the IDE.

Thanks!! :)

**Comment by franco-maroni** [comment]
Hi Marc,
sorry if reply only now but I had limited access to the internet in the last days.
To wrap up, the official Storm DTSM profile is not supported yet, and we are working to support it in the next release (that will be, I think, in a couple of weeks).
The "redundant" plugin is **it.polimi.dice.profiles** (name "_DICE Profiles Polimi_"). 
We will remove it from the verification update site in the next release. 
Since currently the Verification plugin included in the IDE is quite incomplete (is not possible yet to launch a complete verification task) and we will apply several changes in the next days, you can also remove it now if you think it creates too much confusion. 
Anyway, we will let you know as soon as the new version of the tool, supporting the new profile, will be available.

**Comment by franco-maroni** [comment]
it.polimi.dice.profiles has been removed in the latest release of DICE IDE (v0.1.2).
